version: '{build}'
os: Visual Studio 2015 Preview
init: []
install: []
build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmake
- msbuild json.sln
test_script:
- json_unit.exe
