version: '{build}'

environment:
  matrix:
    - os: Visual Studio 2015
      COMPILER: mingw
      platform: x86
      FLAGS: ""
      GENERATOR: MinGW Makefiles

    - os: Visual Studio 2015
      platform: x86
      FLAGS: ""
      GENERATOR: Visual Studio 14 2015

    - os: Visual Studio 2017
      platform: x86
      FLAGS: ""
      GENERATOR: Visual Studio 15 2017

    - os: Visual Studio 2017
      platform: x86
      FLAGS: "/permissive- /std:c++latest /utf-8"
      GENERATOR: Visual Studio 15 2017

    - os: Visual Studio 2015
      platform: x64
      FLAGS: ""
      GENERATOR: Visual Studio 14 2015

    - os: Visual Studio 2017
      platform: x64
      FLAGS: ""
      GENERATOR: Visual Studio 15 2017

    - os: Visual Studio 2017
      platform: x64
      FLAGS: "/permissive- /std:c++latest /utf-8"
      GENERATOR: Visual Studio 15 2017

matrix:
  fast_finish: true

init:
  - cmake --version
  - msbuild /version

install:
  - if "%COMPILER%"=="mingw" set PATH=C:\MinGW\bin;%PATH%

before_build:
  - cmake . -G "%GENERATOR%" -DCMAKE_CXX_FLAGS="%FLAGS%" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"

build_script:
  - cmake --build . --config Release

test_script:
  - ctest -C Release -V -j
