name: macOS

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  xcode_1:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [12.4, 12.3, 12.2, 12.1.1, 12.1, 12, 11.7, 11.6, 11.5, 11.4.1, 11.3.1, 11.2.1, 10.3]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DJSON_BuildTests=On -DJSON_FastTests=ON
      - name: build
        run: cmake --build build --parallel 10
      - name: test
        run: cd build ; ctest -j 10 --output-on-failure

  xcode_2:
    runs-on: macos-12
    strategy:
      matrix:
        xcode: [13.3.1, 13.3, 13.2.1, 13.2, 13.1]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DJSON_BuildTests=On -DJSON_FastTests=ON
      - name: build
        run: cmake --build build --parallel 10
      - name: test
        run: cd build ; ctest -j 10 --output-on-failure

  xcode_standards:
    runs-on: macos-latest
    strategy:
      matrix:
        standard: [11, 14, 17, 20]
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DJSON_BuildTests=On -DJSON_TestStandards=${{ matrix.standard }}
      - name: build
        run: cmake --build build --parallel 10
      - name: test
        run: cd build ; ctest -j 10 --output-on-failure
